# Generated by Django 2.2.3 on 2019-07-28 10:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_full_name', models.CharField(max_length=120)),
                ('recvier_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='Invalid phone number.')])),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('postal_address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
