# Generated by Django 2.2.3 on 2019-09-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_favoritesproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='recvier_phone_number',
            new_name='reciver_phone_number',
        ),
    ]
