# Generated by Django 2.2.3 on 2019-11-01 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191010_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10,10}$', message='Invalid postal code')]),
        ),
    ]
