export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const ADD_NOTIF = "ADD_NOTIF";
export const REMOVE_NOTIF = "REMOVE_NOTIF";

export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const CREATE_ADDRESS = "CREATE_ADDRESSES";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export const FETCH_FAVORITE_PRODUCTS = "FETCH_FAVORITE_PRODUCTS";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
