# Generated by Django 2.2.3 on 2019-10-18 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_remove_cartitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=125)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('send_factor', models.BooleanField(default=False)),
                ('shiping_method', models.CharField(choices=[('NR', 'Normal'), ('EX', 'Express')], max_length=10)),
                ('shiping_status', models.CharField(choices=[('PR', 'Preparation'), ('DP', 'Delivery to post'), ('DC', 'Delivery to customer')], max_length=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Cart')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.ReciverInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
