# Generated by Django 2.2.3 on 2019-07-30 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
        ('profiles', '0002_favoritesproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('send_factor', models.BooleanField(default=False)),
                ('shiping_method', models.CharField(choices=[('NR', 'Normal'), ('EX', 'Express')], max_length=10)),
                ('shiping_status', models.CharField(choices=[('PR', 'Preparation'), ('DP', 'Delivery to post'), ('DC', 'Delivery to customer')], max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
