# Generated by Django 2.2.3 on 2019-11-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191116_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_method',
            new_name='shipping_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shiping_status',
            new_name='shipping_status',
        ),
    ]
