# Generated by Django 2.2.3 on 2019-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191116_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='4224', editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
