# Generated by Django 2.2.3 on 2019-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191028_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_count',
        ),
        migrations.AddField(
            model_name='size',
            name='available_count',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='products.Size'),
        ),
    ]
